name: github_scanner
description: A CLI application that makes it easy to find information about users and repositories on GitHub.
version: 0.0.0
homepage: https://github.com/renatoathaydes/github-scanner
author: renato <renato@athaydes.com>

environment:
  sdk: '>=2.4.1 <3.0.0'

dependencies:
  meta: ^1.1.7
  cli_repl: ^0.2.0+1
  ansicolor: ^1.0.2
  open_url: ^1.0.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
  dartle: ^0.1.0

#dependency_overrides:
#  dartle:
#    path: ../dartle

executables:
  gh-scanner: