name: Dart CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: renatoathaydes/setup-dart@releases/v0
      with:
        architecture: ia32
    - name: Install dependencies
      run: pub.bat get
    - name: Run tests
      run: pub.bat run test
