name: Dart CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dart
      run: choco install dart-sdk
    - name: Update environment
      run: source ~/.bashrc
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
